# Generated by Django 4.2.26 on 2025-12-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(help_text='URL-friendly identifier for this menu', max_length=255, unique=True),
        ),
    ]
